apiVersion: v1
kind: ConfigMap
metadata:
  name: start-script
data:
  prepvs.sh: |
    #!/bin/bash
    set -eux

    echo ${USONIC_VS_LANEMAP}

    cnt=0
    while read line
    do
        if [ ${line:0:1} = '#' ]; then
            continue
        fi
        cnt=$(expr $cnt + 1)
        lhs=$(echo $line | cut -d: -f1)
        rhs=veth$cnt
        ip link del $lhs || true
        ip link del $rhs || true
        ip link add $lhs type veth peer name $rhs
        ip link set up dev $lhs
        ip link set up dev $rhs
    done < ${USONIC_VS_LANEMAP}
  start.sh: | 
    #!/bin/sh
    set -eux

    REDIS_HOST='-s /var/run/redis/redis.sock'

    redis-cli ${REDIS_HOST} flushall

    for daemon in syncd:syncd intfmgrd:intfmgrd orchagent:orchagent portsyncd:portsyncd neighsyncd:neighsyncd vlanmgrd:vlanmgrd;
    do
        redis-cli -n 3 ${REDIS_HOST} hset $daemon LOGOUTPUT STDERR;
    done

    $(dirname $0)/prepvs.sh
