apiVersion: v1
data:
  lanemap.ini: |
    Ethernet1:1,2,3,4
    Ethernet2:5,6,7,8
  port_config.ini: |
    Ethernet1 1,2,3,4
    Ethernet2 5,6,7,8
  sai.profile: |
    SAI_VS_SWITCH_TYPE=SAI_VS_SWITCH_TYPE_BCM56850
    SAI_VS_INTERFACE_LANE_MAP_FILE=/etc/usonic/lanemap.ini
kind: ConfigMap
metadata:
  name: usonic-config
