name: ci
on:
  workflow_dispatch:
  pull_request:
  pull_request_target:
    types: [labeled]
env:
  K: sudo k3s kubectl
jobs:
  build-frr:
    if: ${{ !( ( github.event_name == 'pull_request' ) && ( github.event.pull_request.head.repo.fork == true ) ) }}
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      file: ./docker/build.Dockerfile
      targets: >-
        ["debug", "run"]
